apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-rds
  namespace: dev
spec:
  components:
    - name: dev-db
      type: aws-rds
      properties:
        create_db_subnet_group: true
        db_subnet_group_description: This is the subnet group description
        db_subnet_group_name: dbsubnetgroup
        subnet_ids: ["subnet-0f8de9a5b69205ce5", "subnet-02335369468be2b7b", "subnet-079f42a9d954241aa"]
        vpc_security_group_ids: ["sg-0d1abc48b59fa6f38"]
        instance_class: "db.m5.large"
        identifier: dev-db
        username: masteruser
        engine: postgres
        engine_version: "14.1"
        family: "postgres14"
        account_name: dev
        skip_final_snapshot: true
        publicly_accessible: true
        allocated_storage: 27
        password: resuretsam
        writeConnectionSecretToRef:
          name: dev-db-conn

  workflow:
    steps:
      - name: deploy-dev-db
        type: apply-component
        properties:
          component: dev-db
      - name: dev-notification
        type: webhook-notification
        properties:
          slack:
            url:
              secretRef:
                name: my-secret
                key: slack
            message:
              text: "Successfully apply the database in dev cluster."
