apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
spec:
  components:
  - name: my-app
    type: webservice
    properties:
      image: ghcr.io/fogdong/nocalhost-demo:master-28917c57-1635860530
      port: 9080
    traits:
    - properties:
        image: go
        port: 9080
        gitUrl: https://github.com/bmutziu/nocalhost-demo.git
        sync:
          type: sendReceive
        debug:
          remoteDebugPort: 9009
      type: nocalhost
    - properties:
        domain: test.127.0.0.1.nip.io
        http:
          /: 9080
      type: gateway
  workflow:
    steps:
    - name: default
      properties:
        component: my-app
      type: apply-component
