apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra-gitops
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/bmutziu/nocalhost-demo
      pullInterval: 1m
      git:
        branch: master
      path: ./release/infrastructure
